name: build

on:
  create:
    tags:
      - v*

env:
  DOTNET_NOLOGO: 1 # Disable the .NET welcome message
  DOTNET_CLI_TELEMETRY_OPTOUT: 1 # Opt out of the .NET SDK telemetry feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Install .NET 5 SDK
      uses: actions/setup-dotnet@v1.8.2

    - name: Build
      run: dotnet build --configuration Release --verbosity minimal

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: NuGet packages
        path: |
          artifacts/*.nupkg
          artifacts/*.snupkg
          
    - name: Push NuGet packages to NuGet
      if: ${{ startsWith(github.ref, 'refs/tags/v') }} # Only for a tag
      run: dotnet nuget push "artifacts/**.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

    - name: Create GitHub Release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }} # Only for a tag
      uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
